"""add token fields to message

Revision ID: 6baae09184b0
Revises: 4f6b9e0a2c31
Create Date: 2026-08-03 17:43:17.610195

"""

from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6baae09184b0"
down_revision: Union[str, Sequence[str], None] = "4f6b9e0a2c31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("model", sa.String(length=50), nullable=True))
    op.add_column(
        "messages",
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "messages",
        sa.Column(
            "completion_tokens", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "messages",
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "total_tokens")
    op.drop_column("messages", "completion_tokens")
    op.drop_column("messages", "prompt_tokens")
    op.drop_column("messages", "model")
    # ### end Alembic commands ###
