"""add user memories

Revision ID: e5bc1ceee72c
Revises: e7f8a9b0c1d2
Create Date: 2026-08-15 15:35:32.199216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bc1ceee72c'
down_revision: Union[str, Sequence[str], None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.drop_index(op.f('ix_rag_chunk_embeddings_embedding_ivfflat'), table_name='rag_chunk_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_rag_chunks_document_index'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_documents_user_status_created'), table_name='rag_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rag_documents_user_status_created'), 'rag_documents', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_rag_chunks_document_index'), 'rag_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_chunk_embeddings_embedding_ivfflat'), 'rag_chunk_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###
